services:
  app:
    container_name: crypto_platform
    build: .
    environment:
      DEBUG: 1
    volumes:
      - .:/code
    ports:
      - "8081:8081"
    restart: on-failure
    network_mode: host
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/wallet_data_new
volumes:
  db:
    driver: local