services:
  app:
    container_name: crypto_platform
    build: .
    working_dir: /
    environment:
      DEBUG: 1
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/wallet_data_new
volumes:
  db:
    driver: local
