
  version: 2.1
  orbs:
    python: circleci/python@2.1.1
  workflows:
    main:
      jobs:
        - build
  jobs:
    build:
      docker: 
        - image: cimg/python:3.11.1
      steps:
        - checkout
        - python/install-packages:
            pkg-manager: poetry
        - run:
            name: "Test it"
            # pytest would have to be defined in pyproject.toml
            # inline packages are not allowed with poetry install
            command: |
              poetry run pytest --version