"""added update models

Revision ID: 016d99cad3b6
Revises:
Create Date: 2022-11-22 00:23:39.775045

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "016d99cad3b6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "address",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("blockchain_type", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "address_updates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value_usd", sa.Float(), nullable=True),
        sa.Column("time", sa.BigInteger(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("value_pct", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index("ix_book_id", table_name="book")
    op.drop_table("book")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("year_published", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="book_pkey"),
    )
    op.create_index("ix_book_id", "book", ["id"], unique=False)
    op.drop_table("address_updates")
    op.drop_table("address")
    # ### end Alembic commands ###
