"""added fk to aggregbalanceupdate

Revision ID: 023fc481d598
Revises: 016d99cad3b6
Create Date: 2022-11-22 01:12:23.424762

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "023fc481d598"
down_revision = "016d99cad3b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "address_updates", sa.Column("address_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "address_updates", "address", ["address_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "address_updates", type_="foreignkey")
    op.drop_column("address_updates", "address_id")
    # ### end Alembic commands ###
